# Generated by Django 3.2.13 on 2022-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
