# Generated by Django 3.2.13 on 2022-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_alter_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(default='-1', max_length=2000),
        ),
    ]
