# Generated by Django 3.2.8 on 2022-07-01 12:26

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_auto_20220701_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(default=secrets.token_hex, max_length=512),
        ),
    ]
