# Generated by Django 3.2.8 on 2022-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0005_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(default='JJJZvAApcTTHfRqa6eUUYKU-03Rj3jBnqeFLL3kmncA', max_length=512),
        ),
    ]
