# Generated by Django 3.2.8 on 2022-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0006_alter_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(default='-rT7g_fSINBiW3EqAYLxKpwy8Gclf2pr2_xnaFYM-_c', max_length=512),
        ),
    ]
