# Generated by Django 3.2.13 on 2022-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0007_alter_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(default='xmqXXzmPfBQBgJGJCAqYmUnPLHW5sUqA0zmgT25kfP8', max_length=512),
        ),
    ]
