# Generated by Django 3.2.13 on 2022-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0008_alter_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(default='8BIugz0vbvua0feqAy5rC6xXraPtH-ng1QaVFCl0Y8U', max_length=512),
        ),
    ]
